version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FlaskAWS"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zkrq2ayg81w6"
s3_prefix = "FlaskAWS"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
